# Generated by Django 5.2.17 on 2026-08-16 08:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Inquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=160)),
                ('email', models.EmailField(max_length=254)),
                ('topic', models.CharField(blank=True, max_length=120)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Opportunity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=180)),
                ('slug', models.SlugField(unique=True)),
                ('category', models.CharField(choices=[('scholarship', 'Scholarship'), ('visa', 'Student Visa'), ('job', 'Job')], max_length=30)),
                ('status', models.CharField(choices=[('open', 'Open now'), ('coming', 'Coming soon')], default='open', max_length=20)),
                ('country', models.CharField(max_length=80)),
                ('region', models.CharField(default='Europe', max_length=20)),
                ('deadline', models.DateTimeField()),
                ('summary', models.TextField()),
                ('description', models.TextField()),
                ('eligibility', models.JSONField(default=list)),
                ('required_documents', models.JSONField(default=list)),
                ('featured', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['deadline', 'title'],
            },
        ),
        migrations.CreateModel(
            name='SuccessStory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('destination', models.CharField(max_length=160)),
                ('quote', models.TextField()),
                ('consent_confirmed', models.BooleanField(default=False)),
                ('published', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=160)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=40)),
                ('nationality', models.CharField(blank=True, max_length=80)),
                ('current_location', models.CharField(blank=True, max_length=120)),
                ('education_level', models.CharField(blank=True, max_length=120)),
                ('statement', models.TextField(blank=True)),
                ('document_links', models.JSONField(blank=True, default=list)),
                ('status', models.CharField(choices=[('received', 'Received'), ('reviewing', 'Reviewing'), ('needs_info', 'Needs information'), ('submitted', 'Submitted')], default='received', max_length=30)),
                ('consent_to_contact', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('opportunity', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='applications', to='opportunities.opportunity')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
