# Generated by Django 5.2.17 on 2026-08-16 09:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opportunities', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='email',
            field=models.EmailField(db_index=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('payment_required', 'Payment required'), ('received', 'Received'), ('reviewing', 'Reviewing'), ('needs_info', 'Needs information'), ('approved', 'Approved'), ('rejected', 'Not approved')], default='payment_required', max_length=30),
        ),
        migrations.CreateModel(
            name='ApplicationStatusEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('payment_required', 'Payment required'), ('received', 'Received'), ('reviewing', 'Reviewing'), ('needs_info', 'Needs information'), ('approved', 'Approved'), ('rejected', 'Not approved')], max_length=30)),
                ('note', models.CharField(blank=True, max_length=240)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_events', to='opportunities.application')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='PaymentRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField(default=2000)),
                ('currency', models.CharField(default='TBD', max_length=8)),
                ('provider', models.CharField(blank=True, choices=[('momo', 'MoMo'), ('airtel', 'Airtel Money')], max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('integration_pending', 'Integration pending'), ('paid', 'Paid'), ('failed', 'Failed')], default='integration_pending', max_length=30)),
                ('provider_reference', models.CharField(blank=True, max_length=160)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('application', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='opportunities.application')),
            ],
        ),
        migrations.CreateModel(
            name='SavedOpportunity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(db_index=True, max_length=254)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('opportunity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_by', to='opportunities.opportunity')),
            ],
            options={
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('email', 'opportunity'), name='unique_saved_opportunity')],
            },
        ),
    ]
