# Generated by Django 5.2.17 on 2026-08-16 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opportunities', '0002_application_updated_at_alter_application_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='owner_open_id',
            field=models.CharField(blank=True, db_index=True, max_length=120),
        ),
        migrations.AddField(
            model_name='savedopportunity',
            name='owner_open_id',
            field=models.CharField(blank=True, db_index=True, max_length=120),
        ),
    ]
