# Generated by Django 5.2.17 on 2026-08-16 09:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opportunities', '0003_application_owner_open_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentrecord',
            name='currency',
            field=models.CharField(default='RWF', max_length=8),
        ),
        migrations.CreateModel(
            name='StaffNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('application_submitted', 'Application submitted'), ('application_status', 'Application status changed'), ('payment_status', 'Payment status changed')], max_length=40)),
                ('title', models.CharField(max_length=180)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('application', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='staff_notifications', to='opportunities.application')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
