# Generated by Django 5.2.17 on 2026-08-16 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opportunities', '0004_alter_paymentrecord_currency_staffnotification'),
    ]

    operations = [
        migrations.AddField(
            model_name='opportunity',
            name='deadline_note',
            field=models.CharField(blank=True, max_length=180),
        ),
        migrations.AddField(
            model_name='opportunity',
            name='source_name',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='opportunity',
            name='source_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='opportunity',
            name='source_verified_at',
            field=models.DateField(blank=True, null=True),
        ),
    ]
