# Generated by Django 5.2.17 on 2026-08-17 10:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opportunities', '0006_application_document_metadata'),
    ]

    operations = [
        migrations.CreateModel(
            name='GuestAccessToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(db_index=True, max_length=254)),
                ('token_hash', models.CharField(max_length=64, unique=True)),
                ('purpose', models.CharField(choices=[('verify', 'Email verification'), ('status', 'Status tracking'), ('claim', 'Application claim')], max_length=20)),
                ('expires_at', models.DateTimeField(db_index=True)),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guest_access_tokens', to='opportunities.application')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['application', 'purpose', 'expires_at'], name='opportuniti_applica_1b7e96_idx')],
            },
        ),
    ]
