# Generated by Django 5.2.17 on 2026-08-17 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opportunities', '0007_guestaccesstoken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guestaccesstoken',
            name='purpose',
            field=models.CharField(choices=[('status', 'Status tracking'), ('claim', 'Application claim')], max_length=20),
        ),
    ]
