import type { Opportunity, OpportunityCategory, OpportunityStatus } from "./api";

const make = (id: number, title: string, slug: string, category: OpportunityCategory, country: string, region: string, deadline: string, summary: string, source_name: string, source_url: string, deadline_note: string, status: OpportunityStatus = "open"): Opportunity => ({
  id, title, slug, category, category_label: category === "job" ? "Job opening" : category === "visa" ? "Student visa" : "Scholarship", status, status_label: status === "open" ? "Open now" : "Coming soon", country, region, deadline, summary,
  description: `${summary} Review the official source for current eligibility, documents, and application timing before taking action.`,
  eligibility: ["Route-specific eligibility", "Relevant academic or professional preparation", "Current official requirements"],
  required_documents: ["Passport or national ID", "Academic or professional records", "Statement or role-specific documents"], featured: false, deadline_note, source_name, source_url, source_verified_at: "2026-08-16",
});

export const additionalLocalOpportunities: Opportunity[] = [
  make(11, "France Excellence Eiffel Scholarship", "france-excellence-eiffel-scholarship", "scholarship", "France", "Europe", "2027-01-08T23:59:00Z", "French Ministry scholarship route for international master's and doctoral applicants.", "Campus France", "https://www.campusfrance.org/en/france-excellence-eiffel-scholarship-program", "Annual call; institution nomination deadlines may be earlier."),
  make(12, "Swedish Institute Scholarships", "swedish-institute-scholarships", "scholarship", "Sweden", "Europe", "2027-02-15T23:59:00Z", "Fully funded Swedish Institute scholarship route for eligible international master's applicants.", "Swedish Institute", "https://si.se/en/apply/scholarships/", "Annual window; confirm eligible countries and current dates."),
  make(13, "NL Scholarship", "nl-scholarship-netherlands", "scholarship", "Netherlands", "Europe", "2027-05-01T23:59:00Z", "Official Dutch scholarship information for non-EEA students at participating institutions.", "Study in NL", "https://www.studyinnl.org/finances/nl-scholarship", "Institution deadlines vary; check the participating institution."),
  make(14, "Stipendium Hungaricum", "stipendium-hungaricum", "scholarship", "Hungary", "Europe", "2027-01-15T23:59:00Z", "Hungarian government scholarship route through partner-country and programme calls.", "Tempus Public Foundation", "https://stipendiumhungaricum.hu/", "Annual call; partner-country deadlines may differ."),
  make(15, "Government of Ireland Postgraduate Scholarship", "government-of-ireland-postgraduate-scholarship", "scholarship", "Ireland", "Europe", "2026-10-01T16:00:00Z", "Irish Research Council funding route for research master's and doctoral applicants.", "Irish Research Council", "https://research.ie/funding/goipg/", "Annual call; confirm the current deadline and disciplines.", "coming"),
  make(16, "Global Wales Postgraduate Scholarship", "global-wales-postgraduate-scholarship", "scholarship", "United Kingdom", "Europe", "2027-05-31T23:59:00Z", "Postgraduate scholarship information for eligible international applicants at Welsh universities.", "Study in Wales", "https://www.studyinwales.ac.uk/scholarships/", "Participating-university deadlines vary."),
  make(17, "Swiss Government Excellence Scholarships", "swiss-government-excellence-scholarships", "scholarship", "Switzerland", "Europe", "2026-11-30T23:59:00Z", "Swiss Confederation route for selected postgraduate researchers, artists, and doctoral candidates.", "Swiss Government", "https://www.sbfi.admin.ch/sbfi/en/home/education/scholarships-and-grants/swiss-government-excellence-scholarships.html", "Deadlines vary by country and category."),
  make(18, "EU Careers — EPSO Opportunities", "eu-careers-epso-opportunities", "job", "European Union", "Europe", "2027-12-31T23:59:00Z", "Official EU careers portal for competitions, temporary roles, contract agents, and traineeships.", "EU Careers", "https://eu-careers.europa.eu/", "Dynamic portal; each vacancy or competition has its own closing date."),
  make(19, "Global Korea Scholarship", "global-korea-scholarship", "scholarship", "South Korea", "Asia", "2027-03-31T23:59:00Z", "South Korean government scholarship route for international applicants.", "Study in Korea", "https://www.studyinkorea.go.kr/en/sub/gks/allnew_invite.do", "Annual call; embassy and university deadlines vary."),
  make(20, "Singapore International Graduate Award", "singapore-international-graduate-award", "scholarship", "Singapore", "Asia", "2026-12-01T23:59:00Z", "A*STAR-supported doctoral research route for international graduates.", "A*STAR", "https://www.a-star.edu.sg/singa-scholarship", "Multiple intakes may be available; verify the current deadline."),
  make(21, "Hong Kong PhD Fellowship Scheme", "hong-kong-phd-fellowship-scheme", "scholarship", "Hong Kong", "Asia", "2026-12-01T23:59:00Z", "Competitive fellowship route for international doctoral applicants.", "Hong Kong Research Grants Council", "https://cerg1.ugc.edu.hk/hkpfs/index.html", "Annual round; university and scheme deadlines should be checked."),
  make(22, "ADB-Japan Scholarship Program", "adb-japan-scholarship-program", "scholarship", "Japan", "Asia", "2027-04-30T23:59:00Z", "Graduate route for qualified citizens of eligible ADB developing member countries.", "Asian Development Bank", "https://www.adb.org/work-with-us/careers/japan-scholarship-program", "Institution-specific deadlines vary."),
  make(23, "Brunei Darussalam Government Scholarship", "brunei-darussalam-government-scholarship", "scholarship", "Brunei", "Asia", "2027-02-15T23:59:00Z", "Brunei government scholarship route for foreign students.", "Ministry of Foreign Affairs Brunei", "https://www.mfa.gov.bn/pages/scholarship.aspx", "Annual academic-session call; confirm the current notice.", "coming"),
  make(24, "Malaysia International Scholarship", "malaysia-international-scholarship", "scholarship", "Malaysia", "Asia", "2027-06-30T23:59:00Z", "Malaysian government postgraduate scholarship route for eligible international applicants.", "Malaysia Ministry of Higher Education", "https://biasiswa.mohe.gov.my/INTER/index.php", "Call timing varies; check the official ministry portal.", "coming"),
  make(25, "Chinese Government Scholarship", "chinese-government-scholarship", "scholarship", "China", "Asia", "2027-04-30T23:59:00Z", "China Scholarship Council route for international applicants.", "China Scholarship Council", "https://www.campuschina.org/", "Deadlines vary by category, embassy, and university."),
  make(26, "ICCR A2A Scholarships", "iccr-a2a-scholarships", "scholarship", "India", "Asia", "2027-04-30T23:59:00Z", "India's official foreign-student scholarship application portal.", "Indian Council for Cultural Relations", "https://a2ascholarships.iccr.gov.in/", "Annual portal window; confirm country-specific instructions.", "coming"),
  make(27, "JASSO Scholarship Support", "jasso-scholarship-support", "scholarship", "Japan", "Asia", "2027-03-31T23:59:00Z", "Japan Student Services Organization scholarship information for privately financed international students and exchange participants.", "Study in Japan / JASSO", "https://www.studyinjapan.go.jp/en/planning/scholarships/jasso-scholarships/", "Application timing and recommendation capacity vary by institution or exchange agreement."),
  make(28, "OIST Graduate School", "oist-graduate-school", "scholarship", "Japan", "Asia", "2027-04-15T23:59:00Z", "Interdisciplinary graduate research route at OIST.", "OIST", "https://www.oist.jp/admissions", "Admissions rounds vary; check the official calendar."),
  make(29, "KAIST International Student Scholarship", "kaist-international-student-scholarship", "scholarship", "South Korea", "Asia", "2027-05-31T23:59:00Z", "KAIST international admissions route with scholarship information.", "KAIST", "https://admission.kaist.ac.kr/intl-undergraduate/", "Deadlines vary by intake and study level.", "coming"),
  make(30, "UN Volunteers International Assignments", "un-volunteers-international-assignments", "job", "International", "Asia", "2027-12-31T23:59:00Z", "Official UN Volunteers portal for development and humanitarian assignments.", "United Nations Volunteers", "https://app.unv.org/", "Dynamic portal; each assignment has its own closing date."),
];
