from datetime import datetime, timezone

from django.core.management.base import BaseCommand
from opportunities.models import Opportunity
from .additional_routes import ADDITIONAL_ROUTES


ROUTES = [
    {"title": "Global Excellence Scholarship", "slug": "global-excellence-scholarship", "category": "scholarship", "status": "open", "country": "Netherlands", "region": "Europe", "deadline": "2026-10-28T23:59:00Z", "summary": "A merit-based route preview for ambitious international students building the next generation of ideas.", "description": "A planning-led scholarship route preview focused on programme research, statement preparation, and a clear application calendar.", "eligibility": ["Bachelor's degree or equivalent", "Strong academic record", "Evidence of leadership or community impact"], "required_documents": ["Passport or national ID", "Academic transcripts", "Statement of purpose", "One academic reference"], "featured": True},
    {"title": "Japan Student Visa Guidance", "slug": "japan-student-visa-guidance", "category": "visa", "status": "open", "country": "Japan", "region": "Asia", "deadline": "2026-09-18T23:59:00Z", "summary": "A step-by-step route preview for preparing a confident student visa application for Japan.", "description": "Understand the required documents, timeline, financial evidence, and next steps for a Japan study plan.", "eligibility": ["Confirmed admission or application in progress", "Valid passport", "Proof of financial readiness"], "required_documents": ["Passport", "Certificate of eligibility or school documents", "Financial evidence", "Accommodation plan"], "featured": True},
    {"title": "Nordic Graduate Talent Route", "slug": "nordic-graduate-talent-route", "category": "job", "status": "coming", "country": "Sweden", "region": "Europe", "deadline": "2026-12-02T23:59:00Z", "summary": "A curated route preview for early-career talent exploring graduate roles with global teams.", "description": "An upcoming route preview for CV positioning, employer research, and relocation planning.", "eligibility": ["Recent graduate or final-year student", "Relevant portfolio or experience", "Professional English"], "required_documents": ["CV", "Portfolio or work samples", "Degree certificate or expected graduation letter"], "featured": False},
    {"title": "South Korea Study Pathway", "slug": "south-korea-study-pathway", "category": "visa", "status": "coming", "country": "South Korea", "region": "Asia", "deadline": "2027-01-14T23:59:00Z", "summary": "Prepare early for a focused study route preview in one of Asia's dynamic education hubs.", "description": "Join the early interest list for upcoming South Korea study and visa support.", "eligibility": ["Planning to study in South Korea", "Academic profile aligned with the target institution", "Willingness to prepare early"], "required_documents": ["Passport", "Academic records", "Personal statement", "Financial plan"], "featured": False},
    {"title": "France Campus Scholarship Route", "slug": "france-campus-scholarship-route", "category": "scholarship", "status": "open", "country": "France", "region": "Europe", "deadline": "2026-11-20T23:59:00Z", "summary": "Editorial route preview for students preparing a competitive postgraduate application in France.", "description": "A planning-led route preview focused on programme research and statement preparation.", "eligibility": ["Relevant undergraduate background", "Strong academic record", "Clear study plan"], "required_documents": ["Passport", "Academic transcripts", "Statement of purpose", "Reference letter"], "featured": False},
    {"title": "Germany Study Preparation Route", "slug": "germany-study-preparation-route", "category": "visa", "status": "open", "country": "Germany", "region": "Europe", "deadline": "2026-10-16T23:59:00Z", "summary": "A practical route preview for students planning study, financial evidence, and visa preparation in Germany.", "description": "Build an informed Germany study plan with a structured document checklist and timeline.", "eligibility": ["Offer or active programme search", "Valid passport", "Evidence of financial planning"], "required_documents": ["Passport", "Admission documents", "Financial evidence", "Accommodation plan"], "featured": False},
    {"title": "Ireland Graduate Roles Route", "slug": "ireland-graduate-roles-route", "category": "job", "status": "coming", "country": "Ireland", "region": "Europe", "deadline": "2027-01-30T23:59:00Z", "summary": "A future-facing route preview for graduates exploring international roles with growing teams in Ireland.", "description": "Join the early list for practical guidance on CV positioning and relocation planning.", "eligibility": ["Final-year student or recent graduate", "Relevant portfolio", "Professional communication skills"], "required_documents": ["CV", "Portfolio", "Degree or expected graduation letter"], "featured": False},
    {"title": "Malaysia Student Visa Route", "slug": "malaysia-student-visa-route", "category": "visa", "status": "open", "country": "Malaysia", "region": "Asia", "deadline": "2026-11-08T23:59:00Z", "summary": "A clear preparation route preview for students considering Malaysia as their next study destination.", "description": "Understand the core preparation steps, documents, and timeline for a Malaysia study plan.", "eligibility": ["Study plan aligned with a recognised institution", "Valid passport", "Financial readiness"], "required_documents": ["Passport", "Admission or application evidence", "Academic records", "Financial plan"], "featured": False},
    {"title": "Taiwan Research Scholarship Route", "slug": "taiwan-research-scholarship-route", "category": "scholarship", "status": "coming", "country": "Taiwan", "region": "Asia", "deadline": "2027-02-12T23:59:00Z", "summary": "An upcoming route preview for research-minded students preparing an international academic profile.", "description": "Prepare early with guidance on research fit, academic evidence, and a compelling statement.", "eligibility": ["Research or postgraduate interest", "Relevant academic preparation", "Clear academic goals"], "required_documents": ["Passport", "Transcripts", "Research statement", "Academic reference"], "featured": False},
    {"title": "Singapore Early-Career Roles Route", "slug": "singapore-early-career-roles-route", "category": "job", "status": "coming", "country": "Singapore", "region": "Asia", "deadline": "2027-03-05T23:59:00Z", "summary": "An upcoming route preview for early-career talent building a focused international job search.", "description": "Join the early list for support with role research, application positioning, and relocation questions.", "eligibility": ["Recent graduate or early-career professional", "Relevant skills or portfolio", "Professional English"], "required_documents": ["CV", "Portfolio or work samples", "Qualification evidence"], "featured": False},
]


ROUTES.extend(ADDITIONAL_ROUTES)

VERIFIED_OVERRIDES = {
    "global-excellence-scholarship": {"title": "Chevening Scholarship — 2027–2028", "country": "United Kingdom", "deadline": datetime(2026, 10, 6, 11, 0, tzinfo=timezone.utc), "summary": "Official UK government-backed scholarship route for future leaders applying for postgraduate study.", "description": "Chevening supports one-year master's study in the UK and asks applicants to apply through their country or territory page.", "deadline_note": "Official deadline: 6 October 2026 at 11:00 UTC.", "source_name": "Chevening", "source_url": "https://www.chevening.org/scholarships/application-timeline/", "source_verified_at": "2026-08-16"},
    "japan-student-visa-guidance": {"title": "MEXT Japanese Government Scholarship", "category": "scholarship", "summary": "Official Japan scholarship route with embassy and university recommendation paths.", "deadline_note": "Deadline varies by country embassy or university; check the official source.", "source_name": "Study in Japan", "source_url": "https://www.studyinjapan.go.jp/en/planning/scholarships/mext-scholarships/", "source_verified_at": "2026-08-16"},
    "nordic-graduate-talent-route": {"title": "UN Human Rights Representative — P-5", "status": "open", "country": "Kyrgyzstan", "region": "Asia", "deadline": datetime(2026, 9, 10, 23, 59, tzinfo=timezone.utc), "summary": "Official UN Careers vacancy with OHCHR in Bishkek, covering the Central Asia multi-country office.", "description": "This P-5 role is listed on the official UN Careers portal and includes responsibilities for the OHCHR Central Asia multi-country office.", "deadline_note": "Official UN Careers deadline: 10 September 2026.", "source_name": "UN Careers", "source_url": "https://careers.un.org/jobSearchDescription/281339", "source_verified_at": "2026-08-16", "eligibility": ["P-5 level experience", "Human rights affairs expertise", "Required UN languages and qualifications"], "required_documents": ["UN Careers profile", "CV", "Qualification evidence", "Role-specific documents"]},
    "south-korea-study-pathway": {"title": "EURES Europe Job Search", "category": "job", "status": "open", "country": "European Union", "region": "Europe", "summary": "Official European employment portal with live country and region job searches.", "description": "EURES publishes changing vacancy listings and directs jobseekers to country and regional searches; always confirm the individual vacancy deadline on the official portal.", "deadline_note": "Dynamic portal: individual vacancy deadlines vary; check the official source.", "source_name": "EURES", "source_url": "https://eures.europa.eu/index_en", "source_verified_at": "2026-08-16", "eligibility": ["Jobseeker eligible for the target vacancy", "Role-specific qualifications", "Work authorization or mobility readiness"], "required_documents": ["CV", "Qualifications", "Work authorization details", "Role-specific documents"]},
}

VERIFIED_OVERRIDES.update({
    "france-campus-scholarship-route": {"title": "Erasmus Mundus Joint Masters", "category": "scholarship", "status": "open", "country": "European Union", "region": "Europe", "deadline": datetime(2027, 1, 31, 23, 59, tzinfo=timezone.utc), "deadline_note": "Programme deadlines vary; official guidance says most applications fall between October and January.", "source_name": "Erasmus+", "source_url": "https://erasmus-plus.ec.europa.eu/opportunities/individuals/students/erasmus-mundus-joint-masters", "source_verified_at": "2026-08-16"},
    "germany-study-preparation-route": {"title": "DAAD Scholarship Database", "category": "scholarship", "status": "open", "country": "Germany", "region": "Europe", "deadline_note": "Deadlines vary by programme; check each official DAAD listing.", "source_name": "DAAD", "source_url": "https://www.daad.de/en/studying-in-germany/scholarships/", "source_verified_at": "2026-08-16"},
    "ireland-graduate-roles-route": {"title": "EURAXESS Research Jobs", "category": "job", "status": "open", "country": "Europe", "region": "Europe", "deadline_note": "Dynamic portal: individual vacancy deadlines vary; check the official source.", "source_name": "EURAXESS", "source_url": "https://euraxess.ec.europa.eu/jobs", "source_verified_at": "2026-08-16"},
    "malaysia-student-visa-route": {"title": "MYFutureJobs Malaysia", "category": "job", "status": "open", "country": "Malaysia", "region": "Asia", "deadline_note": "Dynamic portal: individual vacancy deadlines vary; check the official source.", "source_name": "MYFutureJobs", "source_url": "https://www.myfuturejobs.gov.my/", "source_verified_at": "2026-08-16"},
    "taiwan-research-scholarship-route": {"title": "Taiwan Scholarship", "category": "scholarship", "status": "open", "country": "Taiwan", "region": "Asia", "deadline_note": "Application windows vary by Taiwan representative office; check the official source.", "source_name": "Taiwan Scholarship", "source_url": "https://taiwanscholarship.moe.gov.tw/", "source_verified_at": "2026-08-16"},
    "singapore-early-career-roles-route": {"title": "Singapore Careers Portal", "category": "job", "status": "open", "country": "Singapore", "region": "Asia", "deadline_note": "Dynamic portal: individual vacancy deadlines vary; check the official source.", "source_name": "Careers@Gov", "source_url": "https://www.careers.gov.sg/", "source_verified_at": "2026-08-16"},
})

VERIFIED_OVERRIDES.update({
    "japan-student-visa-guidance": {"title": "MEXT Japanese Government Scholarship", "category": "scholarship", "deadline_note": "Deadline varies by country embassy or university; check the official source.", "source_name": "Study in Japan", "source_url": "https://www.studyinjapan.go.jp/en/planning/scholarships/mext-scholarships/", "source_verified_at": "2026-08-16", "description": "The MEXT route is administered through embassy recommendation or university recommendation. Applicants must follow the current instructions published by the relevant Japanese authority.", "eligibility": ["Country-specific MEXT eligibility", "Academic preparation", "Health and language requirements where applicable"], "required_documents": ["Passport", "Academic transcripts", "Recommendation or application forms", "Programme-specific documents"]},
    "france-campus-scholarship-route": {"title": "Erasmus Mundus Joint Masters", "category": "scholarship", "status": "open", "country": "European Union", "region": "Europe", "deadline": datetime(2027, 1, 31, 23, 59, tzinfo=timezone.utc), "deadline_note": "Programme deadlines vary; official guidance says most applications fall between October and January.", "source_name": "Erasmus+", "source_url": "https://erasmus-plus.ec.europa.eu/opportunities/individuals/students/erasmus-mundus-joint-masters", "source_verified_at": "2026-08-16", "description": "Erasmus Mundus applicants select a specific joint master's programme from the official catalogue and follow that programme's eligibility and application instructions.", "eligibility": ["Relevant bachelor's degree", "Programme-specific eligibility", "International study readiness"], "required_documents": ["Passport", "Academic transcripts", "Motivation statement", "Programme-specific documents"]},
    "germany-study-preparation-route": {"title": "DAAD Scholarship Database", "category": "scholarship", "status": "open", "deadline_note": "Deadlines vary by programme; check each official DAAD listing.", "source_name": "DAAD", "source_url": "https://www.daad.de/en/studying-in-germany/scholarships/", "source_verified_at": "2026-08-16", "description": "DAAD maintains a searchable scholarship database. Each funding programme states its own academic, language, country, and deadline requirements.", "eligibility": ["International student or graduate", "Programme-specific eligibility", "Academic preparation"], "required_documents": ["Passport", "Academic records", "Programme-specific documents", "Motivation statement"]},
    "ireland-graduate-roles-route": {"title": "EURAXESS Research Jobs", "category": "job", "status": "open", "country": "Europe", "region": "Europe", "deadline_note": "Dynamic portal: individual vacancy deadlines vary; check the official source.", "source_name": "EURAXESS", "source_url": "https://euraxess.ec.europa.eu/jobs", "source_verified_at": "2026-08-16", "description": "EURAXESS lists research vacancies and funding calls. Applicants should open the individual vacancy to confirm the role, employer, eligibility, and closing date.", "eligibility": ["Research or technical profile", "Role-specific qualifications", "International mobility interest"], "required_documents": ["CV", "Research profile", "Qualifications", "Role-specific documents"]},
    "malaysia-student-visa-route": {"title": "MYFutureJobs Malaysia", "category": "job", "status": "open", "deadline_note": "Dynamic portal: individual vacancy deadlines vary; check the official source.", "source_name": "MYFutureJobs", "source_url": "https://www.myfuturejobs.gov.my/", "source_verified_at": "2026-08-16", "description": "MYFutureJobs is Malaysia's national employment portal. Jobseekers should use the official listing to confirm employer, eligibility, closing date, and work authorization requirements.", "eligibility": ["Role-specific eligibility", "Relevant qualifications", "Malaysia work authorization or route eligibility"], "required_documents": ["CV", "Qualifications", "Work authorization details", "Role-specific documents"]},
    "taiwan-research-scholarship-route": {"title": "Taiwan Scholarship", "category": "scholarship", "status": "open", "deadline_note": "Application windows vary by Taiwan representative office; check the official source.", "source_name": "Taiwan Scholarship", "source_url": "https://taiwanscholarship.moe.gov.tw/", "source_verified_at": "2026-08-16", "description": "The Taiwan Scholarship portal publishes the current scholarship framework and directs applicants to the relevant Taiwan representative office for its application window and requirements.", "eligibility": ["Scholarship-specific eligibility", "Academic preparation", "Country or representative-office requirements"], "required_documents": ["Passport", "Academic transcripts", "Study plan", "Representative-office forms"]},
    "singapore-early-career-roles-route": {"title": "Singapore Careers Portal", "category": "job", "status": "open", "deadline_note": "Dynamic portal: individual vacancy deadlines vary; check the official source.", "source_name": "Careers@Gov", "source_url": "https://www.careers.gov.sg/", "source_verified_at": "2026-08-16", "description": "Careers@Gov publishes Singapore public-service vacancies with role-specific requirements and closing dates. Applicants should verify the individual vacancy before applying.", "eligibility": ["Role-specific eligibility", "Relevant qualifications", "Professional communication"], "required_documents": ["CV", "Qualifications", "Role-specific documents"]},
})


class Command(BaseCommand):
    help = "Seed the expanded editorial opportunity route catalog."

    def handle(self, *args, **options):
        for route in ROUTES:
            values = dict(route)
            slug = values.pop("slug")
            values["deadline"] = datetime.fromisoformat(values["deadline"].replace("Z", "+00:00"))
            values.update(VERIFIED_OVERRIDES.get(slug, {}))
            Opportunity.objects.update_or_create(slug=slug, defaults=values)
        self.stdout.write(self.style.SUCCESS(f"Seeded {len(ROUTES)} opportunity routes."))
