from datetime import datetime, timezone

from django.core.management.base import BaseCommand
from opportunities.models import Opportunity


ROUTES = [
    {"title": "Global Excellence Scholarship", "slug": "global-excellence-scholarship", "category": "scholarship", "status": "open", "country": "Netherlands", "region": "Europe", "deadline": "2026-10-28T23:59:00Z", "summary": "A merit-based route preview for ambitious international students building the next generation of ideas.", "description": "A planning-led scholarship route preview focused on programme research, statement preparation, and a clear application calendar.", "eligibility": ["Bachelor's degree or equivalent", "Strong academic record", "Evidence of leadership or community impact"], "required_documents": ["Passport or national ID", "Academic transcripts", "Statement of purpose", "One academic reference"], "featured": True},
    {"title": "Japan Student Visa Guidance", "slug": "japan-student-visa-guidance", "category": "visa", "status": "open", "country": "Japan", "region": "Asia", "deadline": "2026-09-18T23:59:00Z", "summary": "A step-by-step route preview for preparing a confident student visa application for Japan.", "description": "Understand the required documents, timeline, financial evidence, and next steps for a Japan study plan.", "eligibility": ["Confirmed admission or application in progress", "Valid passport", "Proof of financial readiness"], "required_documents": ["Passport", "Certificate of eligibility or school documents", "Financial evidence", "Accommodation plan"], "featured": True},
    {"title": "Nordic Graduate Talent Route", "slug": "nordic-graduate-talent-route", "category": "job", "status": "coming", "country": "Sweden", "region": "Europe", "deadline": "2026-12-02T23:59:00Z", "summary": "A curated route preview for early-career talent exploring graduate roles with global teams.", "description": "An upcoming route preview for CV positioning, employer research, and relocation planning.", "eligibility": ["Recent graduate or final-year student", "Relevant portfolio or experience", "Professional English"], "required_documents": ["CV", "Portfolio or work samples", "Degree certificate or expected graduation letter"], "featured": False},
    {"title": "South Korea Study Pathway", "slug": "south-korea-study-pathway", "category": "visa", "status": "coming", "country": "South Korea", "region": "Asia", "deadline": "2027-01-14T23:59:00Z", "summary": "Prepare early for a focused study route preview in one of Asia's dynamic education hubs.", "description": "Join the early interest list for upcoming South Korea study and visa support.", "eligibility": ["Planning to study in South Korea", "Academic profile aligned with the target institution", "Willingness to prepare early"], "required_documents": ["Passport", "Academic records", "Personal statement", "Financial plan"], "featured": False},
    {"title": "France Campus Scholarship Route", "slug": "france-campus-scholarship-route", "category": "scholarship", "status": "open", "country": "France", "region": "Europe", "deadline": "2026-11-20T23:59:00Z", "summary": "Editorial route preview for students preparing a competitive postgraduate application in France.", "description": "A planning-led route preview focused on programme research and statement preparation.", "eligibility": ["Relevant undergraduate background", "Strong academic record", "Clear study plan"], "required_documents": ["Passport", "Academic transcripts", "Statement of purpose", "Reference letter"], "featured": False},
    {"title": "Germany Study Preparation Route", "slug": "germany-study-preparation-route", "category": "visa", "status": "open", "country": "Germany", "region": "Europe", "deadline": "2026-10-16T23:59:00Z", "summary": "A practical route preview for students planning study, financial evidence, and visa preparation in Germany.", "description": "Build an informed Germany study plan with a structured document checklist and timeline.", "eligibility": ["Offer or active programme search", "Valid passport", "Evidence of financial planning"], "required_documents": ["Passport", "Admission documents", "Financial evidence", "Accommodation plan"], "featured": False},
    {"title": "Ireland Graduate Roles Route", "slug": "ireland-graduate-roles-route", "category": "job", "status": "coming", "country": "Ireland", "region": "Europe", "deadline": "2027-01-30T23:59:00Z", "summary": "A future-facing route preview for graduates exploring international roles with growing teams in Ireland.", "description": "Join the early list for practical guidance on CV positioning and relocation planning.", "eligibility": ["Final-year student or recent graduate", "Relevant portfolio", "Professional communication skills"], "required_documents": ["CV", "Portfolio", "Degree or expected graduation letter"], "featured": False},
    {"title": "Malaysia Student Visa Route", "slug": "malaysia-student-visa-route", "category": "visa", "status": "open", "country": "Malaysia", "region": "Asia", "deadline": "2026-11-08T23:59:00Z", "summary": "A clear preparation route preview for students considering Malaysia as their next study destination.", "description": "Understand the core preparation steps, documents, and timeline for a Malaysia study plan.", "eligibility": ["Study plan aligned with a recognised institution", "Valid passport", "Financial readiness"], "required_documents": ["Passport", "Admission or application evidence", "Academic records", "Financial plan"], "featured": False},
    {"title": "Taiwan Research Scholarship Route", "slug": "taiwan-research-scholarship-route", "category": "scholarship", "status": "coming", "country": "Taiwan", "region": "Asia", "deadline": "2027-02-12T23:59:00Z", "summary": "An upcoming route preview for research-minded students preparing an international academic profile.", "description": "Prepare early with guidance on research fit, academic evidence, and a compelling statement.", "eligibility": ["Research or postgraduate interest", "Relevant academic preparation", "Clear academic goals"], "required_documents": ["Passport", "Transcripts", "Research statement", "Academic reference"], "featured": False},
    {"title": "Singapore Early-Career Roles Route", "slug": "singapore-early-career-roles-route", "category": "job", "status": "coming", "country": "Singapore", "region": "Asia", "deadline": "2027-03-05T23:59:00Z", "summary": "An upcoming route preview for early-career talent building a focused international job search.", "description": "Join the early list for support with role research, application positioning, and relocation questions.", "eligibility": ["Recent graduate or early-career professional", "Relevant skills or portfolio", "Professional English"], "required_documents": ["CV", "Portfolio or work samples", "Qualification evidence"], "featured": False},
]


class Command(BaseCommand):
    help = "Seed the expanded editorial opportunity route catalog."

    def handle(self, *args, **options):
        for route in ROUTES:
            values = dict(route)
            values["deadline"] = datetime.fromisoformat(values["deadline"].replace("Z", "+00:00"))
            Opportunity.objects.update_or_create(slug=values.pop("slug"), defaults=values)
        self.stdout.write(self.style.SUCCESS(f"Seeded {len(ROUTES)} opportunity routes."))
