import { Link } from "wouter";
import { ArrowRight, Bell, FileText, Loader2, ShieldCheck } from "lucide-react";
import { useAuth } from "@/_core/hooks/useAuth";
import AccountControls from "@/components/AccountControls";

export default function AdminDashboard() {
  const { user, loading } = useAuth();
  if (loading) return <main className="route-state"><div className="container"><Loader2 className="spin" /><span className="eyebrow">Checking administrator access</span><h1>Preparing your<br /><em>admin dashboard.</em></h1></div></main>;
  if (!user) return <main className="route-state"><div className="container"><span className="eyebrow">Administrator access</span><h1>Sign in to open<br /><em>this dashboard.</em></h1><p>This workspace is reserved for authorized administrators.</p><Link href="/dashboard" className="button button-dark">Return to account access</Link></div></main>;
  if (user.role !== "admin") return <main className="route-state"><div className="container"><span className="eyebrow">Access not authorized</span><h1>This is not your<br /><em>dashboard.</em></h1><p>Your account is recognized as {user.role === "staff" ? "staff" : "an applicant"}. The system keeps each dashboard separate.</p><Link href={user.role === "staff" ? "/staff" : "/dashboard/end-user"} className="button button-dark">Open my dashboard <ArrowRight size={17} /></Link></div></main>;
  return <main className="dashboard-page"><div className="container dashboard-wrap"><AccountControls /><div className="dashboard-heading"><div><span className="eyebrow">Administrator dashboard</span><h1>Lead with<br /><em>clarity.</em></h1><p>{user.email || user.name}</p></div><div className="secure-label"><ShieldCheck size={15} /> Admin credentials verified</div></div><section className="dashboard-stats"><div><span>Account type</span><strong>Admin</strong></div><div><span>Review access</span><strong>Full</strong></div><div><span>Workspace</span><strong>Protected</strong></div></section><section className="dashboard-section"><div className="section-heading"><div><span className="eyebrow">Management tools</span><h2>Choose a protected workspace.</h2></div></div><div className="saved-grid"><Link href="/staff/applications" className="saved-card saved-card-link"><FileText size={22} /><span className="detail-category">Submissions & payments</span><h3>Review applications</h3><p>Search submissions, update statuses, monitor payments, and download applicant documents.</p><span className="text-button dark-button">Open staff review <ArrowRight size={15} /></span></Link><Link href="/staff/notifications" className="saved-card saved-card-link"><Bell size={22} /><span className="detail-category">Team operations</span><h3>Notification center</h3><p>Review internal alerts and manage unread staff notifications.</p><span className="text-button dark-button">Open notifications <ArrowRight size={15} /></span></Link></div></section></div></main>;
}
